import os
import re
import uuid
import json
import statistics
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ── Rate limiter ────────────────────────────────────────────────────────────
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Groq client ─────────────────────────────────────────────────────────────
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ── Audit log (in-memory list; replace with SQLite in later milestones) ─────
_audit_log: list[dict] = []


# ────────────────────────────────────────────────────────────────────────────
# Signal 1 — LLM semantic assessment
# ────────────────────────────────────────────────────────────────────────────

def get_llm_score(text: str) -> float:
    """
    Ask Groq to estimate the probability that `text` is AI-generated.
    Returns a float in [0.0, 1.0].  Falls back to 0.5 on any error so the
    pipeline never hard-crashes because of a bad API response.
    """
    prompt = (
        "You are an AI content attribution system. Analyse the text below and "
        "estimate the probability (0.0 to 1.0) that it was generated by an AI "
        "language model rather than written by a human.\n"
        "0.0 = certainly human-written, 1.0 = certainly AI-generated.\n\n"
        "Return ONLY valid JSON in this format: {\"ai_probability\": <float>}\n"
        "Do not include any explanation.\n\n"
        f"TEXT:\n{text}"
    )

    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=32,
        )
        raw = response.choices[0].message.content.strip()
        data = json.loads(raw)
        score = float(data["ai_probability"])
        return max(0.0, min(1.0, score))   # clamp to [0, 1]

    except Exception as exc:
        app.logger.warning("LLM signal failed: %s — defaulting to 0.5", exc)
        return 0.5


# ────────────────────────────────────────────────────────────────────────────
# Signal 2 — Stylometric heuristics
# ────────────────────────────────────────────────────────────────────────────

def _tokenise_sentences(text: str) -> list[str]:
    """Split text into sentences on .!? boundaries."""
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s for s in sentences if s.strip()]


def _type_token_ratio(words: list[str]) -> float:
    """Vocabulary diversity over the first 200 words. Higher = more diverse."""
    sample = words[:200]
    if len(sample) == 0:
        return 0.5
    return len(set(w.lower() for w in sample)) / len(sample)


def _sentence_length_variance(sentences: list[str]) -> float:
    """Standard deviation of word counts per sentence. Higher = more varied."""
    if len(sentences) < 2:
        return 0.0
    lengths = [len(s.split()) for s in sentences]
    return statistics.stdev(lengths)


def _punctuation_density(text: str, words: list[str]) -> float:
    """Count of expressive punctuation marks divided by word count."""
    if not words:
        return 0.0
    marks = re.findall(r'[;:—–()\u2026]', text)   # excludes plain commas
    return len(marks) / len(words)


def _normalise(value: float, ai_end: float, human_end: float) -> float:
    """
    Linear normalisation so that ai_end → 1.0 and human_end → 0.0.
    Works whether ai_end < human_end (e.g. TTR: low = AI) or
    ai_end > human_end (would be reversed scale).
    Result is clamped to [0, 1].
    """
    if ai_end == human_end:
        return 0.5
    score = (value - human_end) / (ai_end - human_end)
    return max(0.0, min(1.0, score))


def get_style_score(text: str) -> dict:
    """
    Compute three stylometric sub-metrics and combine them into a single
    style_score in [0, 1] where 1 = likely AI-generated.

    Returns a dict with the combined score and the three raw sub-scores
    so they can be logged individually.
    """
    words = re.findall(r"\b\w+\b", text)
    sentences = _tokenise_sentences(text)

    ttr = _type_token_ratio(words)
    variance = _sentence_length_variance(sentences)
    punct = _punctuation_density(text, words)

    # Normalise each sub-metric: lower TTR / lower variance / lower punct → AI
    # Anchors recalibrated from observed sub-score ranges on short texts:
    #   TTR:      human writing clusters 0.82–0.88, AI similar but slightly lower
    #             → widen the band so differences register
    #   variance: short texts all fall 4–10; AI tighter (< 6), human looser (> 9)
    #   punct:    AI near 0.0, human uses occasional expressive marks (> 0.02)
    ttr_norm      = _normalise(ttr,      ai_end=0.75, human_end=0.92)
    variance_norm = _normalise(variance, ai_end=4.0,  human_end=12.0)
    punct_norm    = _normalise(punct,    ai_end=0.0,  human_end=0.04)

    combined = (ttr_norm + variance_norm + punct_norm) / 3.0

    return {
        "style_score":    round(combined, 4),
        "ttr":            round(ttr, 4),
        "sent_variance":  round(variance, 4),
        "punct_density":  round(punct, 4),
        "ttr_norm":       round(ttr_norm, 4),
        "variance_norm":  round(variance_norm, 4),
        "punct_norm":     round(punct_norm, 4),
    }


# ────────────────────────────────────────────────────────────────────────────
# Combined confidence scorer
# ────────────────────────────────────────────────────────────────────────────

def get_combined_score(llm_score: float, style_score: float) -> float:
    """
    Weighted average: LLM 65%, stylometric 35%.
    LLM gets higher weight because it captures holistic semantic patterns;
    stylometric is independent but has a known bias toward short casual writing.
    """
    return round((0.65 * llm_score) + (0.35 * style_score), 4)


# ────────────────────────────────────────────────────────────────────────────
# Audit log helpers
# ────────────────────────────────────────────────────────────────────────────

def write_log_entry(entry: dict) -> None:
    _audit_log.append(entry)


def get_log(limit: int = 50) -> list[dict]:
    return _audit_log[-limit:]


def find_log_entry(content_id: str) -> dict | None:
    for entry in _audit_log:
        if entry.get("content_id") == content_id:
            return entry
    return None


# ────────────────────────────────────────────────────────────────────────────
# Routes
# ────────────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON."}), 400

    text = body.get("text", "").strip()
    creator_id = body.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Field 'text' is required and must be non-empty."}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required."}), 400
    if len(text.split()) < 40:
        return jsonify({
            "error": "Text is too short for reliable analysis. Please submit at least 40 words."
        }), 400

    content_id = str(uuid.uuid4())

    # --- Signal 1: LLM semantic assessment ---
    llm_score = get_llm_score(text)

    # --- Signal 2: Stylometric heuristics ---
    style_result = get_style_score(text)
    style_score  = style_result["style_score"]

    # --- Combined confidence score (60% LLM, 40% stylometric) ---
    combined_score = get_combined_score(llm_score, style_score)
    attribution    = _get_attribution(combined_score)
    label          = _generate_label(combined_score)

    entry = {
        "content_id":    content_id,
        "creator_id":    creator_id,
        "timestamp":     datetime.now(timezone.utc).isoformat(),
        "attribution":   attribution,
        "confidence":    combined_score,
        "llm_score":     round(llm_score, 4),
        "style_score":   style_score,
        "ttr":           style_result["ttr"],
        "sent_variance": style_result["sent_variance"],
        "punct_density": style_result["punct_density"],
        "label":         label,
        "status":        "classified",
        "appeal_reasoning":  None,
        "appeal_timestamp":  None,
    }
    write_log_entry(entry)

    return jsonify({
        "content_id":  content_id,
        "attribution": attribution,
        "confidence":  combined_score,
        "llm_score":   round(llm_score, 4),
        "style_score": style_score,
        "label":       label,
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON."}), 400

    content_id        = body.get("content_id", "").strip()
    creator_reasoning = body.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Field 'content_id' is required."}), 400
    if not creator_reasoning:
        return jsonify({"error": "Field 'creator_reasoning' is required and must be non-empty."}), 400

    entry = find_log_entry(content_id)
    if entry is None:
        return jsonify({"error": f"No submission found with content_id '{content_id}'."}), 404

    if entry.get("status") == "under_review":
        return jsonify({
            "error": "An appeal has already been submitted for this content.",
            "content_id": content_id,
            "status": "under_review",
        }), 409

    # Update the existing log entry in place
    entry["status"]           = "under_review"
    entry["appeal_reasoning"] = creator_reasoning
    entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()

    return jsonify({
        "content_id": content_id,
        "status":     "under_review",
        "message":    "Your appeal has been received and will be reviewed by a human moderator.",
    }), 200


@app.route("/log", methods=["GET"])
def log():
    # Optional ?status=under_review filter for human reviewers
    status_filter = request.args.get("status")
    entries = get_log()
    if status_filter:
        entries = [e for e in entries if e.get("status") == status_filter]
    return jsonify({"entries": entries}), 200


# ────────────────────────────────────────────────────────────────────────────
# Attribution and label helpers
# ────────────────────────────────────────────────────────────────────────────

def _get_attribution(score: float) -> str:
    if score < 0.35:
        return "likely_human"
    if score < 0.65:
        return "uncertain"
    return "likely_ai"


def _generate_label(score: float) -> str:
    attribution = _get_attribution(score)

    if attribution == "likely_ai":
        return (
            "⚠ This content was likely generated with AI assistance.\n\n"
            "Our system analysed this submission using two independent methods and found "
            "strong indicators of AI-generated text. This label does not mean the work "
            "has no value — it is provided so you can make an informed decision about "
            "what you're reading.\n\n"
            "If you are the creator and believe this is incorrect, you can submit an "
            "appeal below."
        )
    if attribution == "uncertain":
        return (
            "ℹ Attribution unclear\n\n"
            "Our system found mixed signals in this submission. We could not reliably "
            "determine whether this content was written by a human or generated with AI "
            "assistance. No strong conclusion is drawn either way.\n\n"
            "Creators can submit an appeal at any time to provide additional context."
        )
    return (
        "✓ This content appears to be human-written.\n\n"
        "Our system found no strong indicators of AI generation in this submission. "
        "This is not a guarantee — detection tools are imperfect — but the signals "
        "we measured are consistent with human authorship."
    )


# ────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True)